export const AST_TYPES = {
    LITERAL: 'literal',
    OBJECT_LITERAL: 'object_literal',
    TEMPLATE_LITERAL: 'template_literal',
    ROUTER: 'router',
    ROUTE: 'route',
    EMIT: 'emit',
    BINARY_EXPRESSION: 'binary_expression',
    MEMBER_EXPRESSION: 'member_expression',
    FUNCTION_CALL: 'function_call',
    IMPORT: 'import',
    EXPORT: 'export',
    FUNCTION: 'function',
    IDENTIFIER: 'identifier',
    RETURN: 'return',
    TYPE: 'type',
    ASSIGNMENT: 'assignment',
    EXPRESSION_STATEMENT: 'expression_statement',
} as const;